site_name: Aurelius Enterprise Documentation

theme:
  name: readthedocs
  logo: img/logo.png
  favicon: img/favicon.ico
  search: true

nav:
  - Home: index.md
  - Benefits and Features: benefits-and-features.md
  - Getting Started: getting-started.md
  - Installation and Deployment: installation-and-deployment.md
  - Architecture: architecture.md
  - User Guide: user-guide.md
  - Integrations: integrations.md
  - Support and Maintenance: support-and-maintenance.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed          

extra_css:
  - stylesheets/tabs.css
