site_name: Aurelius Enterprise Documentation

theme:
  name: readthedocs
  logo: img/logo.png
  favicon: img/favicon.ico
  search: true

nav:
  - Getting Started: index.md
  - Benefits and Features: benefits-and-features.md
  - User Stories: user-stories.md
  - Installation and Deployment: installation-and-deployment.md
  - Architecture: architecture.md
  - Integrations: integrations.md
  - Onboarding Data Sources: onboard-datasources.md
  - Frequently Asked Questions: faq.md
  - Support: support.md
  - About Us: about-us.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  
plugins:
  - mermaid2

extra_css:
  - stylesheets/tabs.css
  - stylesheets/icons.css
